version: "3"

services:
    nginx:
        container_name: nginx
        build: 
            context: .
            dockerfile: Dockerfile-nginx
        depends_on:
            - mysql 
        volumes: 
            - ./symfony/:/var/www/symfony/
        ports: 
            - 8080:80
        networks:
            - symfony
    
    mysql:
        container_name: mysql
        image: mysql:8.0.26
        restart: always
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
        environment:
            # MYSQL_USER: user
            # MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database

volumes:
    mysql:

networks:
    symfony: