version: "3"

services:
    nginx:
        container_name: deepez_nginx
        build: 
            context: .
            dockerfile: Dockerfile-nginx
        volumes: 
            - ./symfony/:/var/www/symfony/
        ports: 
            - 80:80
        networks:
            - symfony
    
    symfony:
        container_name: deepez_symfony
        build:
            context: .
            dockerfile: Dockerfile-symfony
        depends_on:
            - mysql
        environment:
            APP_ENV: dev
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony 
    
    mysql:
        container_name: deepez_mysql
        image: mysql:8.0.26
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./database:/var/lib/mysql
        environment:
            # MYSQL_USER: user
            # MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: deepez
        networks:
            - symfony

networks:
    symfony: